### ISSUE TITLE
The template can't create the target directory

### ISSUE THREAD

**Issue by tonicebrian** [spotify/scio.g8#79]
Using the template accepting all default options doesn't work because instead of the target directory there is a file with same name that prevents directory creation.

```
$ sbt new spotify/scio.g8
[info] Loading settings for project global-plugins from plugins.sbt ...
[info] Loading global plugins from /Users/cebriant/.sbt/1.0/plugins
[info] Set current project to borralodedentro (in build file:/Users/cebriant/borralodedentro/)
[info] Set current project to borralodedentro (in build file:/Users/cebriant/borralodedentro/)
name [scio job]:
organization [example]:
DataflowRunner [yes/NO]:
DataflowFlexTemplate [yes/NO]:
FlinkRunner [yes/NO]:
SparkRunner [yes/NO]:

Unknown exception: Directory '/Users/cebriant/borralodedentro/./scio-job' could not be created

$ cat scio-job
{
  "name": "WordCount Example",
  "description": "",
  "parameters": [
    {
      "regexes": [
        "^gs:\/\/[^\n\r]+$"
      ],
      "name": "input",
      "label": "GCS input text file",
      "helpText": "GCS input text file"
    },
    {
      "regexes": [
        "^gs:\/\/[^\n\r]+$"
      ],
      "name": "output",
      "label": "GCS output text file",
      "helpText": "GCS output text file"
    }
  ]
}
```

**Comment by regadas** [comment]
Hi @tonicebrian can't seem to reproduce this. Maybe you are running an outdated sbt version? you might need also to cleanup your sbt cache perhaps.

you can try the following to run it without your env:
```bash
docker run -it  hseeberger/scala-sbt:graalvm-ce-20.0.0-java11_1.3.13_2.13.3 sbt new spotify/scio.g8
```

**Comment by tonicebrian** [comment]
Ok, the version I was using was `1.3.10`, so I've tried with the latest version and with an empty boot folder:

```
sbt -Dsbt.boot.directory=/tmp/sbt-tmp -Dsbt.version=1.3.13 new spotify/scio.g8
```

and it worked. So it seems like I have something in my sbt boot directory.

Any clue on what should I look for? Or how do I clean the sbt cache as you proposed?

**Comment by regadas** [comment]
Do you have a `.g8` in your `$HOME`? try removing that (shot in the dark). If it doesn't work, I guess backing of conf files and starting a new `.sbt` is the best quick and dirty thing you can do (rm .boot and targe should perhaps suffice).
