### ISSUE TITLE
Unknown exception: Directory scio-job could not be created

### ISSUE THREAD

**Issue by tabdulradi** [spotify/scio.g8#97]
Hello, 

Whenever I try to use the template (using the default arguments or other arguments), I get  "Directory could not be created" error. I noticed a file gets created in current directory with the same name as the directory, the content of this file is the same as `/src/main/g8/$if(DataflowFlexTemplate.truthy)$metadata.json$endif$` in this repo. So I went ahead [forked and deleted the file](https://github.com/tabdulradi/scio.g8) and the problem was gone.

I am using macOS Catalina and didn't try on other operating systems.

**Comment by zhongdai** [comment]
I got the same problem, but if I set the `DataflowFlexTemplate` as `yes`, it works.

```
➜  zd sbt new spotify/scio.g8
[info] Loading global plugins from /Users/xzdi2/.sbt/1.0/plugins
[info] Set current project to zd (in build file:/Users/xzdi2/zd/)
[info] Set current project to zd (in build file:/Users/xzdi2/zd/)
name [scio job]: scio-example
organization [example]:
DataflowRunner [yes/NO]: yes
DataflowFlexTemplate [yes/NO]: yes
FlinkRunner [yes/NO]:
SparkRunner [yes/NO]:

Template applied in /Users/xzdi2/zd/./scio-example
```

**Comment by tabdulradi** [comment]
hmm, so I think `$if(DataflowFlexTemplate.truthy)$metadata.json$endif$` was intended to not create the file if `DataflowFlexTemplate=no`, but instead it created the file with the same name as the folder. Looks like a bug in Giter8 tbh.

**Comment by regadas** [comment]
Hi @tabdulradi sorry for late reply!

I can't replicate this. Which sbt version are you running? Also this seems a bit related to https://github.com/spotify/scio.g8/issues/79.

**Comment by nevillelyh** [comment]
Closing. Feel free to re-open if you can reliably repro.
